# Generated by Django 6.0.6 on 2026-06-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_do", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="to_do",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="to_do",
            name="finished_at",
            field=models.DateField(null=True),
        ),
    ]
